### ISSUE TITLE
run command `flutter pub run test_coverage` frozen  in terminal.

### ISSUE THREAD

**Issue by LongXiangGuo** [pulyaevskiy/test-coverage#12]
When execute the `flutter pub run test_coverage`, it aways frozen in terminal. 

yaml:   test_coverage: ^0.3.0

**Comment by LongXiangGuo** [comment]
LSCNM598058:my_timer qxq4633$ flutter pub run test_coverage
Found 2 test files.
Generated test-all script in test/.test_coverage.dart. Please make sure it is added to .gitignore.

**Comment by LongXiangGuo** [comment]
use `flutter test --coverage`  and `genhtml coverage/lcov.info -o coverage/html` could generator html report.

**Comment by pulyaevskiy** [comment]
Yes, flutter has its own coverage tool so no need in using this package. Closing.
