### ISSUE TITLE
Coverage fails intermittently on CircleCI with exit code 255

### ISSUE THREAD

**Issue by shyndman** [pulyaevskiy/test-coverage#14]
```
Unhandled exception:
Tests failed with exit code 255
#0      runTestsAndCollect (package:test_coverage/src/functions.dart:120:5)
<asynchronous suspension>
#1      main (file:///root/.pub-cache/hosted/pub.dartlang.org/test_coverage-0.4.0/bin/test_coverage.dart:51:9)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

We're encountering this exception semi-frequently on our CircleCI builds. Example: https://app.circleci.com/jobs/github/mobxjs/mobx.dart/1944

If you check out our pipelines, many of the failures are the same. Any insight?

Thanks!

**Comment by pulyaevskiy** [comment]
Thanks for reporting! Hard to tell from this output. Would be nice to add a `--debug` option to test_coverage which prints all output from test runner instead of swallowing it.

**Comment by shyndman** [comment]
Hey! I ended up doing essentially that in https://github.com/shyndman/test-coverage

We've since discovered a pretty ordinary-looking test failure seems to be responsible in our case.

I'm closing this off, since the problem is resolved in our case, but yes — more output is better. If there was a `--debug` flag, I'd leave it on all the time.

**Comment by pavanpodila** [comment]
> Thanks for reporting! Hard to tell from this output. Would be nice to add a `--debug` option to test_coverage which prints all output from test runner instead of swallowing it.

Is the flag being considered for an upcoming version?

**Comment by frank06** [comment]
Agree that it would be better to print out everything.

So atm using

```yaml
dev_dependencies:
  test_coverage:
    git: https://github.com/shyndman/test-coverage.git
```
