### ISSUE TITLE
Never completes

### ISSUE THREAD

**Issue by zoechi** [pulyaevskiy/test-coverage#25]
```sh
pub run test_coverage
|
```
The cursor keeps blinking at this location and there is only ever output if one or more tests fail.
If all tests succeed (checked with `pub run test`), `pub run test_coverage` just hangs there forever.
```
Dart SDK version: 2.11.0-213.1.beta (beta) (Unknown timestamp) on "linux_x64"
```

**Comment by zoechi** [comment]
Seems not to be related to this package. It's just that the generated Dart file never completes.

**Comment by long1eu** [comment]
What did you do? :D

**Comment by zoechi** [comment]
dart test --coverage (or similar) is a thing now. No need for an additional package anymore.

**Comment by xamantra** [comment]
@zoechi that only generates json files (`*.vm.json`) and most coverage software uses `lcov.info` file.
You need other libraries to generate the lcov file and those other libraries also hangs up on my computer idk. This is really frustrating. I also tried looking into this issue but didn't help: [--coverage should generate a lcov.info file #1265](https://github.com/dart-lang/test/issues/1265)

**Comment by yoliva** [comment]
any update on this one?
